# Generated by Django 5.1.4 on 2026-09-22 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid_code', models.CharField(max_length=40, verbose_name='航标编号')),
                ('cd_diff', models.FloatField(verbose_name='坎德拉差额')),
                ('dropped_to_failed', models.BooleanField(default=False, verbose_name='由合格掉为不合格')),
                ('created_by', models.CharField(max_length=64, verbose_name='对读生成人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('after', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comparisons_after', to='inspection.inspection')),
                ('before', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comparisons_before', to='inspection.inspection')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
